generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmProfile
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_profile
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =user_id
        max_per_page: 8
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - id
          - user_id
      form:
        display:
          NONE: [User]
        class: DmProfileAdminForm
        fields: {  }
      edit:
        title: "%%user_id%%"
      new: ~
    sortable: false
