generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmWidget
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_widget
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - dm_zone_id
          - module
          - action
          - value
          - css_class
          - created_at
          - updated_at
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - id
          - dm_zone_id
          - module
          - action
          - value
          - css_class
          - created_at
          - updated_at
      form:
        display:
          NONE: [dm_zone_id]
          Value: [value]
          Others: [module, action, css_class]
        class: DmWidgetAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: true
