generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmArea
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_area
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - dm_layout_id
          - dm_page_view_id
          - type
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - id
          - dm_layout_id
          - dm_page_view_id
          - type
      form:
        display:
          NONE: [dm_layout_id, dm_page_view_id]
          Others: [type]
        class: DmAreaAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
