Utils:
  Configuration:
    dmConfigPanel:
      name:         Configuration panel
      credentials:  config_panel
  Translation:
    dmTransUnit:
      name:         Sentence
      model:        TransUnit
      credentials:  translation
  Users:
    dmProfile:
      name:         Profile
      credentials:  user_profile
  Monitoring:
    dmChart:
      name:         Chart
      credentials:  see_chart
    dmLog:
      name:         Log
      credentials:  see_log
  Accessibility:
    dmLang:
      name:         Lang span
      credentials:  accessibility
    dmAbbr:
      name:         Abbreviation
      credentials:  accessibility
  Media:
    dmMediaLibrary:
      name:         Media
      credentials:  media_library
  "Search engine":
    dmSearchEngine:
      name:         Manage index
      credentials:  search_engine
  
Seo:
  Services:
    dmGoogleAnalytics:
      name:         Google analytics
      credentials:  use_google_analytics
    dmGoogleWebmasterTools:
      name:         Google webmaster tools
      credentials:  use_google_webmaster_tools
  Sitemap:
    dmSitemap:
      name:         Generate sitemap
      credentials:  sitemap
  Metas:
    dmAutoSeo:
      name:         Automatic Page
      credentials:  automatic_metas
    dmSeoValidation:
      name:         Seo Validation
      credentials:  metas_validation
  Redirections:
    dmRedirect:
      name:         Url Redirections
      credentials:  url_redirection

Integration:
  Layout:
    dmLayout:
      name:         Layout
      credentials:  layout

System:
  Configuration:
    dmSetting:
      name:         Setting
      credentials:  system
  Log:
    dmSentMail:
      name:         Sent mail
      credentials:  sent_mail
    dmError:
      name:         Error
      credentials:  error_log
  Security:
    dmGuardUser:
      name:         User
      model:        sfGuardUser
      credentials:  security_user
    sfGuardPermission:
      name:         Permission
      model:        sfGuardPermission
      credentials:  security_permission
    sfGuardGroup:
      name:         Group
      model:        sfGuardGroup
      credentials:  security_group
  Dev:
    dmDiagram:
      name:         See diagrams
      credentials:  system
    dmCodeEditor:
      name:         Code Editor
      credentials:  code_editor
    dmConsole:
      name:         Diem Console
      credentials:  system
    dmServer:
      name:         Server
      credentials:  system