default:

  i18n:
    catalogue:            dm
    
  html:
    validate:             yes           # Validates Html in admin ( credential: html_validate_admin )
    doctype:
      name:               'html'       # Doctype ( 'html', 'xhtml' )
      version:            '5'         # Doctype xhtml version ( '1.0', '1.1' ) or html version ( '4', '5' )
    
  pageBar:
    enabled:              true
    
  mediaBar:
    enabled:              yes
    
  admin:
    max_per_page:         [ 3, 5, 10, 15, 20, 30, 50, 100, ∞ ]  # admin lists paginators
    list_truncate:        200                                   # truncate big descriptions in admin lists
    
  console:                # emulate a linux shell
                          # commands available
    commands:             'sf man ll ls pwd cat mkdir rm cp mv touch chmod free df find clear'
    alias:                # aliases available
      'll':               'ls -l'