parameters:

  log_chart.class:            dmLogChart
  log_chart.options:
    name:                     Server

  week_chart.class:           dmWeekChart
  week_chart.options:
    name:                     This Week

  visit_chart.class:          dmVisitChart
  visit_chart.options:
    name:                     Popularity

  content_chart.class:        dmContentChart
  content_chart.options:
    name:                     Activity

  browser_chart.class:        dmBrowserChart
  browser_chart.options:
    name:                     Browsers

  gapi.class:                 dmGapi

  link_tag.class:             dmAdminLinkTag

  theme.options:
    key:                      diem_admin
    path:                     themeAdmin
    name:                     "Admin Theme"

  asset_config.class:         dmAdminAssetConfig

  admin_sort_table_form.class:    dmAdminSortTableForm

  admin_sort_referers_form.class: dmAdminSortReferersForm

  layout_helper.class:        dmAdminLayoutHelper

  admin_menu.class:           dmAdminMenu
    
  sitemap.class:              dmSitemap
  sitemap.options:
    file:                     sitemap.xml
 
services:

  log_chart:
    class:                    %log_chart.class%
    shared:                   false
    arguments:                [ @service_container, %log_chart.options% ]

  week_chart:
    class:                    %week_chart.class%
    shared:                   false
    arguments:                [ @service_container, %week_chart.options% ]

  browser_chart:
    class:                    %browser_chart.class%
    shared:                   false
    arguments:                [ @service_container, %browser_chart.options% ]

  visit_chart:
    class:                    %visit_chart.class%
    shared:                   false
    arguments:                [ @service_container, %visit_chart.options% ]

  content_chart:
    class:                    %content_chart.class%
    shared:                   false
    arguments:                [ @service_container, %content_chart.options% ]

  gapi:
    class:                    %gapi.class%
    shared:                   true
    arguments:                [ %gapi.email%, %gapi.password%, %gapi.auth_token% ]

  link_tag:
    class:                    %link_tag.class%
    shared:                   false
    arguments:                [ %link_tag.source%, %request.context%, @controller ]

  admin_sort_table_form:
    class:                    %admin_sort_table_form.class%
    shared:                   false
    arguments:                [ %admin_sort_form.defaults%, %admin_sort_form.options% ]

  admin_sort_referers_form:
    class:                    %admin_sort_referers_form.class%
    shared:                   false
    arguments:                [ %admin_sort_form.defaults%, %admin_sort_form.options% ]
      
  admin_menu:
    class:                    %admin_menu.class%
    shared:                   true
    arguments:                [ @dispatcher, @user, @i18n, @routing, @module_manager ]

  sitemap:
    class:                    %sitemap.class%
    shared:                   false
    arguments:                [ @dispatcher, @filesystem, %sitemap.options% ]