parameters:

  asset_config.class:         dmAdminAssetConfig

  admin_sort_table_form.class:    dmAdminSortTableForm

  admin_sort_referers_form.class: dmAdminSortReferersForm

  layout_helper.class:        dmAdminLayoutHelper

  admin_menu.class:           dmAdminMenu
    
  sitemap.class:              dmSitemap
  sitemap.options:
    file:                     sitemap.xml
 
services:

  admin_sort_table_form:
    class:                    %admin_sort_table_form.class%
    shared:                   false
    arguments:
      defaults:               %admin_sort_form.defaults%
      options:                %admin_sort_form.options%

  admin_sort_referers_form:
    class:                    %admin_sort_referers_form.class%
    shared:                   false
    arguments:
      defaults:               %admin_sort_form.defaults%
      options:                %admin_sort_form.options%

  layout_helper:
    class:                    %layout_helper.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      user:                   @user
      request:                @request
      response:               @response
      action_stack:           @action_stack
      helper:                 @helper
      
  admin_menu:
    class:                    %admin_menu.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      user:                   @user
      i18n:                   @i18n
      routing:                @routing

  sitemap:
    class:                    %sitemap.class%
    shared:                   false
    arguments:
      dispatcher:             @dispatcher
      filesystem:             @filesystem
      options:                %sitemap.options%