parameters:

  link_tag.class:             dmAdminLinkTag

  theme.options:
    key:                      diem_admin
    path:                     themeAdmin
    name:                     "Admin Theme"

  asset_config.class:         dmAdminAssetConfig

  admin_sort_table_form.class:    dmAdminSortTableForm

  admin_sort_referers_form.class: dmAdminSortReferersForm

  layout_helper.class:        dmAdminLayoutHelper

  admin_menu.class:           dmAdminMenu
    
  sitemap.class:              dmSitemap
  sitemap.options:
    file:                     sitemap.xml
 
services:

  link_tag:
    class:                    %link_tag.class%
    shared:                   false
    arguments:
      source:                 %link_tag.source%
      request_context:        %request.context%
      controller:             @controller

  admin_sort_table_form:
    class:                    %admin_sort_table_form.class%
    shared:                   false
    arguments:
      defaults:               %admin_sort_form.defaults%
      options:                %admin_sort_form.options%

  admin_sort_referers_form:
    class:                    %admin_sort_referers_form.class%
    shared:                   false
    arguments:
      defaults:               %admin_sort_form.defaults%
      options:                %admin_sort_form.options%
      
  admin_menu:
    class:                    %admin_menu.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      user:                   @user
      i18n:                   @i18n
      routing:                @routing

  sitemap:
    class:                    %sitemap.class%
    shared:                   false
    arguments:
      dispatcher:             @dispatcher
      filesystem:             @filesystem
      options:                %sitemap.options%