generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmMedia
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_media
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - dm_media_folder_id
          - file
          - legend
          - author
          - license
          - mime
          - size
          - dimensions
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - id
          - dm_media_folder_id
          - file
          - legend
          - author
          - license
          - mime
          - size
          - dimensions
          - created_at
          - updated_at
      form:
        display:
          NONE: [dm_media_folder_id]
          Others: [file, legend, author, license, mime, size, dimensions]
        class: DmMediaAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
