generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmAbbr
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_abbr
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =name
          - title
        sort:
          - name
          - asc
        max_per_page: 8
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - name
          - title
      form:
        display:
          NONE: [name]
          Others: [title]
        class: DmAbbrAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
