generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmAutoSeo
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_auto_seo
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =name
          - module
          - action
          - slug
          - title
          - h1
          - description
          - keywords
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - name
          - module
          - action
          - slug
          - title
          - h1
          - description
          - keywords
          - created_at
          - updated_at
      form:
        display:
          NONE: [name]
          'Strip words': [strip_words]
          Others: [module, action, slug, title, h1, description, keywords]
        class: DmAutoSeoAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
