generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class:           DmPermission
    theme:                 dmAdmin
    non_verbose_templates: true
    with_show:             false
    route_prefix:          dm_permission
    with_doctrine_route:   true

    config:
      list:
        display: [=name, description, created_at, updated_at]
        sort:
          - name
          - asc
        table_method: joinAll
        table_count_method: ~
        loremize: false

      form:
        display: [name, description, groups_list, users_list]