indexSuccess:

  stylesheets:
    - lib.jgrowl
    - admin.codeEditor
    
  javascripts:
    - lib.ui-tabs
    - lib.jsTree
    - lib.jsTreeCss
    - lib.jgrowl
    - core.codeArea
    - admin.codeEditor
    
   
openFileSuccess:

  stylesheets: []
  javascripts: []
  has_layout:  off