generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmSession
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_session
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - dm_profile_id
          - dm_page_id
          - sess_id
          - last_time
          - arrival_time
          - ip
          - url
          - nb_pages
          - browser_name
          - browser_version
          - platform
          - is_crawler
          - is_rss_reader
          - is_banned
          - is_mobile_device
          - user_agent
          - status_code
          - content_type
          - content_length
          - time
          - history
          - is_cached
          - created_at
          - updated_at
        sort:
          - created_at
          - desc
        max_per_page: 8
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - id
          - is_crawler
          - is_rss_reader
          - is_banned
          - is_mobile_device
          - is_cached
          - sess_id
          - dm_profile_id
          - dm_page_id
          - last_time
          - arrival_time
          - ip
          - url
          - nb_pages
          - browser_name
          - browser_version
          - platform
          - user_agent
          - status_code
          - content_type
          - content_length
          - time
          - history
          - created_at
          - updated_at
      form:
        display:
          NONE: [is_crawler, is_rss_reader, is_banned, is_mobile_device, is_cached, dm_profile_id, dm_page_id]
          History: [history]
          Others: [sess_id, last_time, arrival_time, ip, url, nb_pages, browser_name, browser_version, platform, user_agent, status_code, content_type, content_length, time]
        class: DmSessionAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
