generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmPage
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_page
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - module
          - action
          - record_id
          - is_secure
          - lft
          - rgt
          - level
        sort:
          - id
          - asc
        max_per_page: 8
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - id
          - is_secure
          - module
          - action
          - record_id
          - lft
          - rgt
          - level
      form:
        display:
          NONE: [is_secure]
          Others: [module, action, record_id, lft, rgt, level]
        class: DmPageAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
