generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmPageView
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_page_view
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - dm_layout_id
          - area_list
          - module
          - action
        sort:
          - id
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - id
          - module
          - action
          - dm_layout_id
      form:
        display:
          NONE: [dm_layout_id]
          Others: [module, action]
        class: DmPageViewAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
