config/dm/modules.yml:
  class:          dmModuleManagerConfigHandler
  
config/dm/project.yml:
  class:          sfDefineEnvironmentConfigHandler
  param:
    prefix:       dm_
    
config/dm/assets.yml:
  class:          dmInlineAssetConfigHandler
  
config/dm/widget_types.yml:
  class:          sfSimpleYamlConfigHandler