default:

  i18n:
    class:                  dmFrontI18n
    param:
      database:             default
      source:               dmMySQL
      debug:                off
      cache:
        class:              dmMetaCache

  routing:
    class:                  dmFrontPatternRouting
    param:
      cache:
        class:              dmMetaCache

  request:
    class:                  dmWebRequest

  response:
    class:                  dmFrontWebResponse
    
  logger:
    param:
      loggers:
        sf_web_debug:
          param:
            xdebug_logging: false
            web_debug_class: dmWebDebug
 
  view_cache:
    class:                  dmMetaCache