rendering:    ~

remember_me:
  class:      sfGuardRememberMeFilter

security:
  class:      dmFrontSecurityFilter

dm_init:
  class:      dmFrontInitFilter

cache:        ~

common:
  enabled:    false

execution:    ~