default:

  accessibility:
    access_links:         yes
    
  html:
    doctype:
      name:               'html'        # Doctype ( 'html', 'xhtml' )
      version:            '5'           # Doctype xhtml version ( '1.0', '1.1' ) or html version ( '4', '5' )
      compliance:         'transitional' # Doctype (x)html compliance ( 'strict', 'transitional' )
      validate:           yes           # Validates Html in front ( credential: html_validate_front )

  i18n:
    catalogue:            front
    
  pageBar:
    enabled:              yes
    
  mediaBar:
    enabled:              yes