parameters:

  form_manager.class:         dmFormManager

  doctrine_pager.class:       dmFrontDoctrinePager

  link_tag.class:             dmFrontLinkTag
  link_tag_record.class:      dmFrontLinkTagRecord
  link_tag_page.class:        dmFrontLinkTagPage
  link_tag_media.class:       dmFrontLinkTagMedia
  link_tag_action.class:      dmFrontLinkTagAction
  link_tag_uri.class:         dmFrontLinkTagUri
  link_tag_error.class:       dmFrontLinkTagError

  link_resource.class:        dmFrontLinkResource

  asset_config.class:         dmFrontAssetConfig

  theme_manager.class:        dmThemeManager

  widget_view.class:          dmWidgetBaseView

  layout_helper.class:        dmFrontLayoutHelper

  page_helper.class:          dmFrontPageHelper
  page_helper.view_class:     dmFrontPageHelper
  page_helper.edit_class:     dmFrontPageEditHelper
  
  widget_type_manager.class:  dmWidgetTypeManager
  widget_type_manager.options:
    config_file:              'config/dm/widget_types.yml'        
 
services:

  form_manager:
    class:                    %form_manager.class%
    shared:                   true

  doctrine_pager:
    class:                    %doctrine_pager.class%
    shared:                   false
    arguments:                [ %doctrine_pager.model%, %doctrine_pager.max_per_page% ]

  link_tag:
    class:                    %link_tag.class%
    shared:                   false
    arguments:                [ %link_tag.source%, %request.context% ]

  link_resource:
    class:                    %link_resource.class%
    shared:                   false

  theme_manager:
    class:                    %theme_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @service_container, %theme_manager.options% ]

  widget_view:
    class:                    %widget_view.class%
    shared:                   false
    arguments:                [ @context, %widget_view.type%, %widget_view.data% ]

  page_helper:
    class:                    %page_helper.class%
    shared:                   true
    arguments:                [ @dispatcher, @widget_type_manager, @service_container, @i18n ]

  widget_type_manager:
    class:                    %widget_type_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @cache_manager, @config_cache, @controller, @module_manager, %widget_type_manager.options% ]