parameters:

  asset_config.class:         dmFrontAssetConfig

  theme_manager.class:        dmThemeManager

  widget_view.class:          dmWidgetBaseView

  layout_helper.class:        dmFrontLayoutHelper

  page_helper.class:          dmFrontPageHelper
  page_helper.view_class:     dmFrontPageHelper
  page_helper.edit_class:     dmFrontPageEditHelper
  
  widget_type_manager.class:  dmWidgetTypeManager
  widget_type_manager.options:
    config_file:              'config/dm/widget_types.yml'        
 
services:

  theme_manager:
    class:                    %theme_manager.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      service_container:      @service_container
      options:                %theme_manager.options%

  widget_view:
    class:                    %widget_view.class%
    shared:                   false
    arguments:
      dispatcher:             @dispatcher
      helper:                 @helper
      service_container:      @service_container
      type:                   %widget_view.type%
      data:                   %widget_view.data%

  layout_helper:
    class:                    %layout_helper.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      user:                   @user
      request:                @request
      response:               @response
      action_stack:           @action_stack
      helper:                 @helper

  page_helper:
    class:                    %page_helper.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      widget_type_manager:    @widget_type_manager
      service_container:      @service_container
      i18n:                   @i18n

  widget_type_manager:
    class:                    %widget_type_manager.class%
    shared:                   true
    arguments:
      dispatcher:             @dispatcher
      cache_manager:          @cache_manager
      config_cache:           @config_cache
      controller:             @controller
      options:                %widget_type_manager.options%