parameters:

  html_sitemap.class:         dmFrontHtmlSitemap    # Responsible for building and rendering an HTML sitemap. Not to be confused with the xml sitemap, the HTML one is intended to be displayed on the site.

  page_not_found_handler.class: dmPageNotFoundHandler # Responsible to redirect or forward the user when the request page is not found.

  form_manager.class:         dmFormManager         # Responsible for creating and managing front forms.

  doctrine_pager.class:       dmFrontDoctrinePager  # Responsible for paginating the front doctrine collections, and rendering the pagination links.

  link_tag_record.class:      dmFrontLinkTagRecord  # Responsible for rendering a link tag to a record with the £link helper. Configurable from the graphical configuration panel.
  link_tag_record.options:    []
  
  link_tag_page.class:        dmFrontLinkTagPage    # Responsible for rendering a link tag to a DmPage instance with the £link helper. Configurable from the graphical configuration panel.
  link_tag_page.options:      []
  
  link_tag_media.class:       dmFrontLinkTagMedia   # Responsible for rendering a link tag to a DmMedia instance with the £link helper. Configurable from the graphical configuration panel.
  link_tag_media.options:     []
  
  link_tag_action.class:      dmFrontLinkTagAction  # Responsible for rendering a link tag to a symfony action with the £link helper. Configurable from the graphical configuration panel.
  link_tag_action.options:    []
  
  link_tag_uri.class:         dmFrontLinkTagUri     # Responsible for rendering a link tag to an external uri with the £link helper. Configurable from the graphical configuration panel.
  link_tag_uri.options:       []
  
  link_tag_error.class:       dmFrontLinkTagError   # Responsible for rendering a link tag to an exception with the £link helper. Configurable from the graphical configuration panel.
  link_tag_error.options:     []

  link_resource.class:        dmFrontLinkResource   # Ressource for a link_tag_*.

  asset_config.class:         dmFrontAssetConfig    # Responsible for loading required assets.

  theme_manager.class:        dmThemeManager        # Responsible for managing available themes.

  widget_view.class:          dmWidgetBaseView      # Responsible for rendering a widget.

  layout_helper.class:        dmFrontLayoutHelper   # Responsible for rendering the front layout.

  page_helper.class:          dmFrontPageHelper     # Responsible for rendering the front content.
  page_helper.view_class:     dmFrontPageHelper
  page_helper.edit_class:     dmFrontPageEditHelper
  
  widget_type_manager.class:  dmWidgetTypeManager   # Responsible for managing widget types.
  widget_type_manager.options:
    config_file:              'config/dm/widget_types.yml' # path to the widget type configuration file, relative to the project directory
    
  helper.class:               dmFrontHelper         # Override the core helper options 
 
services:

  html_sitemap:
    class:                    %html_sitemap.class%
    arguments:                [ @helper, %user.culture% ]

  page_not_found_handler:
    class:                    %page_not_found_handler.class%
    shared:                   false
    arguments:                [ @service_container, @dispatcher ]

  form_manager:
    class:                    %form_manager.class%
    arguments:                [ @service_container ]
    shared:                   true

  doctrine_pager:
    class:                    %doctrine_pager.class%
    shared:                   false
    arguments:                [ %doctrine_pager.model%, %doctrine_pager.max_per_page% ]
    calls:
      - [ setContext, [ @context ] ]

  link_tag_record:
    class:                    %link_tag_record.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %context.page%, %request.context%, %link_tag_record.options% ]

  link_tag_page:
    class:                    %link_tag_page.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %context.page%, %request.context%, %link_tag_page.options% ]

  link_tag_media:
    class:                    %link_tag_media.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %request.context%, %link_tag_media.options% ]

  link_tag_action:
    class:                    %link_tag_action.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, @controller, %request.context%, %link_tag_action.options% ]

  link_tag_uri:
    class:                    %link_tag_uri.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, @controller, %request.context%, %link_tag_uri.options% ]

  link_tag_error:
    class:                    %link_tag_error.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %request.context%, %link_tag_error.options% ]

  link_resource:
    class:                    %link_resource.class%
    shared:                   false

  theme_manager:
    class:                    %theme_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @service_container, %theme_manager.options% ]

  widget_view:
    class:                    %widget_view.class%
    shared:                   false
    arguments:                [ @context, %widget_view.type%, %widget_view.data% ]

  page_helper:
    class:                    %page_helper.class%
    shared:                   true
    arguments:                [ @dispatcher, @widget_type_manager, @service_container, @i18n, @helper ]

  widget_type_manager:
    class:                    %widget_type_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @service_container, %widget_type_manager.options% ]