parameters:
  page_helper.class:          dmFrontPageHelper
  widget_type_manager.class:  dmWidgetTypeManager
  widget_type_manager.options:
    config_file:              'config/dm/widget_types.yml'        
 
services:

  page_helper:
    class:                    %page_helper.class%
    shared:                   true
    arguments:
      dispatcher:             %dispatcher%
      dm_context:             %dm_context%

  widget_type_manager:
    class:                    %widget_type_manager.class%
    shared:                   true
    arguments:
      dispatcher:             %dispatcher%
      cache_manager:          @cache_manager
      context:                %context%
      options:                %widget_type_manager.options%