parameters:

  html_sitemap.class:         dmFrontHtmlSitemap

  page_not_found_handler.class: dmPageNotFoundHandler

  form_manager.class:         dmFormManager

  doctrine_pager.class:       dmFrontDoctrinePager

  link_tag_record.class:      dmFrontLinkTagRecord
  link_tag_record.options:    []
  
  link_tag_page.class:        dmFrontLinkTagPage
  link_tag_page.options:      []
  
  link_tag_media.class:       dmFrontLinkTagMedia
  link_tag_media.options:     []
  
  link_tag_action.class:      dmFrontLinkTagAction
  link_tag_action.options:    []
  
  link_tag_uri.class:         dmFrontLinkTagUri
  link_tag_uri.options:       []
  
  link_tag_error.class:       dmFrontLinkTagError
  link_tag_error.options:     []

  link_resource.class:        dmFrontLinkResource

  asset_config.class:         dmFrontAssetConfig

  theme_manager.class:        dmThemeManager

  widget_view.class:          dmWidgetBaseView

  layout_helper.class:        dmFrontLayoutHelper

  page_helper.class:          dmFrontPageHelper
  page_helper.view_class:     dmFrontPageHelper
  page_helper.edit_class:     dmFrontPageEditHelper
  
  widget_type_manager.class:  dmWidgetTypeManager
  widget_type_manager.options:
    config_file:              'config/dm/widget_types.yml'  
    
  helper.class:               dmFrontHelper      
 
services:

  html_sitemap:
    class:                    %html_sitemap.class%
    arguments:                [ @helper, %user.culture% ]

  page_not_found_handler:
    class:                    %page_not_found_handler.class%
    shared:                   false
    arguments:                [ @service_container, @dispatcher ]

  form_manager:
    class:                    %form_manager.class%
    shared:                   true

  doctrine_pager:
    class:                    %doctrine_pager.class%
    shared:                   false
    arguments:                [ %doctrine_pager.model%, %doctrine_pager.max_per_page% ]
    calls:
      - [ setContext, [ @context ] ]

  link_tag_record:
    class:                    %link_tag_record.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %context.page%, %request.context%, %link_tag_record.options% ]

  link_tag_page:
    class:                    %link_tag_page.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %context.page%, %request.context%, %link_tag_page.options% ]

  link_tag_media:
    class:                    %link_tag_media.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %request.context%, %link_tag_media.options% ]

  link_tag_action:
    class:                    %link_tag_action.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, @controller, %request.context%, %link_tag_action.options% ]

  link_tag_uri:
    class:                    %link_tag_uri.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, @controller, %request.context%, %link_tag_uri.options% ]

  link_tag_error:
    class:                    %link_tag_error.class%
    shared:                   false
    arguments:                [ %link_tag.resource%, %request.context%, %link_tag_error.options% ]

  link_resource:
    class:                    %link_resource.class%
    shared:                   false

  theme_manager:
    class:                    %theme_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @service_container, %theme_manager.options% ]

  widget_view:
    class:                    %widget_view.class%
    shared:                   false
    arguments:                [ @context, %widget_view.type%, %widget_view.data% ]

  page_helper:
    class:                    %page_helper.class%
    shared:                   true
    arguments:                [ @dispatcher, @widget_type_manager, @service_container, @i18n, @helper ]

  widget_type_manager:
    class:                    %widget_type_manager.class%
    shared:                   true
    arguments:                [ @dispatcher, @service_container, %widget_type_manager.options% ]