dmWidgetContent:

  title:                []
    # To customize widgets forms and views
    # copy this file to your project config/dm path
    # and set the form_class and view_class values :
    #form_class:        dmWidgetContentTitleForm
    #view_class:        dmWidgetContentTitleView

  link:                 []

  text:                 []

  media:                []
    
  gallery:              []
    
dmWidgetNavigation:

  breadCrumb:           []
    
  menu:                 []
    
dmWidgetAdvanced:

  googleMap:            []
    
  searchForm:           []
    
  searchResults:        []