dmWidgetContent:

# To customize widgets forms and views
# copy this file to your project config/dm path
# and set the form_class and view_class values.
# Example :
# title:
#   form_class:         myTitleForm
#   view_class:         myTitleView
#   cache:              true

  title:
    cache:              true

  link:
    cache:              true

  text:
    cache:              true

  media:
    cache:              true
    
  gallery:
    cache:              true
    
dmWidgetNavigation:

  breadCrumb:
    cache:              true
    
  menu:
    cache:              true
    
dmWidgetAdvanced:

  googleMap:
    cache:              true
    
  searchForm:
    cache:              false
    
  searchResults:
    cache:              false