generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmLang
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_lang
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =name
        sort:
          - name
          - asc
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - name
      form:
        display:
          NONE: [name]
        class: DmLangAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
