generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmZone
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_zone
    with_doctrine_route: false
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =id
          - widgets_list
          - dm_area_id
          - css_class
          - width
        sort:
          - position
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - id
          - dm_area_id
          - css_class
          - width
      form:
        display:
          Others: [dm_area_id, css_class, width]
        class: DmZoneAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: true
