generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmError
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_error
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =name
          - klass
          - description
          - module
          - action
          - uri
          - env
          - created_at
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
      filter:
        display:
          - name
          - klass
          - description
          - module
          - action
          - uri
          - env
          - created_at
      form:
        display:
          NONE: [name]
          Description: [_description]
          Others: [klass, module, action, uri, env]
        class: DmErrorAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
