refresh:
  is_secure:    true
  credential:   clear_cache
  
refreshStep:
  is_secure:    true
  credential:   clear_cache

markdown:
  is_secure:    true
  credential:   admin

thumbnail:
  is_secure:    true
  credential:   admin