js:

  core:
    config:           dmCoreConfig
    plugins:          dmCorePlugins
    editPlugins:      dmCoreEditPlugins
    ctrl:             dmCoreCtrl
    editCtrl:         dmCoreEditCtrl
    form:             dmCoreForm
    tabForm:          dmCoreTabForm
    toolBar:          dmCoreToolBar
    pageBar:          dmCorePageBar
    mediaBar:         dmCoreMediaBar
    auth:             dmCoreAuth
    codeArea:         dmCoreCodeArea
    
  lib:
    symfony_debug:    symfony/debug
    jquery:           jquery/jquery-1.3.2.min
    ui-core:          jquery-ui-18/js/minified/ui.core.min
    ui-position:      jquery-ui-18/js/minified/ui.position.min
    ui-draggable:     jquery-ui-18/js/minified/ui.draggable.min
    ui-datepicker:    jquery-ui-18/js/minified/ui.datepicker.min
    ui-droppable:     jquery-ui-18/js/minified/ui.droppable.min
    ui-sortable:      jquery-ui-18/js/minified/ui.sortable.min
    ui-resizable:     jquery-ui-18/js/minified/ui.resizable.min
    ui-tabs:          jquery-ui-18/js/minified/ui.tabs.min
    ui-dialog:        jquery-ui-18/js/minified/ui.dialog.min
    ui-i18n:          jquery-ui-18/js/minified/i18n/ui.datepicker-%culture%.min
    metadata:         metadata/jquery.metadata.min
    jqtransform:      jqtransform/jquery.jqtransform.min
    form:             form/jquery.form
    jsTree:           jsTree/source/tree_component.min
    jsTreeCss:        jsTree/source/css
    blockUI:          blockUI/jquery.blockUI.min
    jgrowl:           jgrowl/jquery.jgrowl_minimized
    ajaxqueue:        ajaxqueue/jquery.ajaxQueue
    cookie:           cookie/jquery.cookie.min
    markitup:         markitup/jquery.markitup.min
    markitupSet:      dmMarkitup/sets/markdown/set
    fancybox:         fancybox/jquery.fancybox-1.2.1.pack
    expose:           expose/jquery.expose-1.0.1.min
    qtip:             qtip/jquery.qtip-1.0.0-rc3.min
    hotkeys:          hotkeys/jquery.hotkeys-0.7.9.min
    jmap:             jmap/jquery.jmap.min

css:

  core:
    util:             util
    editMode:         editMode
    interface:        interface
    sprites:          sprites
    sprite16:         sprite16
    sprite24:         sprite24
    toolBar:          toolBar
    pageBar:          pageBar
    mediaBar:         mediaBar
    form:             form
    auth:             auth
    browsers:         browsers
    
  lib:
    symfony_debug:    symfony/debug
    reset:            reset/reset
    ui:               jquery-ui/css/jquery-ui-1.7.2.custom
    ui-datepicker:    jquery-ui/css/jquery-ui-datepicker.1.7.2
    ui-dialog:        jquery-ui/css/jquery-ui-dialog.1.7.2
    ui-resizable:     jquery-ui/css/jquery-ui-resizable.1.7.2
    ui-tabs:          jquery-ui/css/jquery-ui-tabs.1.7.2
    jqtransform:      jqtransform/jqtransform
    jgrowl:           jgrowl/jquery.jgrowl
    markitup:         dmMarkitup/skins/markitup/style
    markitupSet:      dmMarkitup/sets/markdown/style
    fancybox:         fancybox/jquery.fancybox