default:

  i18n:                                 # internationalization
    cultures:             [ en ]        # Available cultures
  
  search:                               # Internal search engine
    fields:                             # Pages fields to search in, with boost level
      id:                 0             # page doctrine identifier
      slug:               3             # page description meta
      name:               3             # page name ( used as link name to this page )
      title:              2             # page title
      h1:                 4             # page h1
      description:        2             # page description meta
      indexable_content:  1             # page html content
    slop:                 10            # distance allowed between two words in a searched phrase
  
  cache:                                # Cache management
    apc:                  true          # (RECOMMENDED) Use Apc if available on current server

  error:                                # What to do when an error occured
    mail_superadmin:      false         # Send mail to superadmin ( uses superadmin's profile's email )
    store_in_db:          true          # Store error in database
    
  js:
    compress:             true          # (RECOMMENDED) Performance : Minifies javascripts and put them into a single compressed file
    cdn:                                # use cdn to load libraries
      enabled:            <?php echo !sfConfig::get('sf_debug') ?> # (RECOMMENDED) Will use cdn to load javascript libraries faster
      lib.jquery:         'http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js'
    api:                                # external apis
      gmap:                             # google maps api http://code.google.com/apis/maps/
                                        # to configure the api key, go to the settings panel in the admin application.
        version:          3             # api version
        sensor:           false         # use a sensor to determine a user's location
        url:              http://maps.google.com/maps?file=api&v=%version%&sensor=%sensor%&key=%key%
    
  css:
    compress:             true          # (RECOMMENDED) Performance : Minifies stylesheets and put them into a single compressed file
    
  seo:                                  # Search engine optimization configuration
    use_keywords:         true          # Keywords are useless for seo, but you can use them if you want
    truncate:                           # Max length for meta fields. Can not exceed 255 characters
      slug:               255
      name:               255
      title:              80
      h1:                 255
      description:        160
      keywords:           255
    sitemap:                            # see http://sitemaps.org
      path:               sitemap.xml   # relative path from web dir where diem will generate the sitemap

  orm:                                  # Doctrine ORM configuration
                                        # More configuration : please use ProjectConfiguration::configureDoctrine method
    identifier_fields:    [ name, title, slug, subject, id ] # Fields used to represent a record with a string
    cache_enabled:        true          # (RECOMMENDED) Use doctrine query cache. No side effect, automatic cache invalidation )
    cache_result_enabled: true          # (RECOMMENDED) Use doctrine result cache where query->dmCache() is called
    cache_result_enabled_default: false # Use doctrine result cache on every query ( performance gain, possible issues )
    
  backup:                               # keep a copy of files modified by Dm code editors
    enabled:              true          # (RECOMMENDED) enable backup
  
  web_debug:                            # web debug panel configuration
    only_html_response:   true          # will skip web debug panel display on non html response
    config_fast_dump:     true          # use print_r instead of sfYaml::dump to show config in web debug panel. ( ~40x faster )
    
  toolBar:
    flavour:              blue          # the toolbar flavour. Diem default values: grey, blue, green, brown, black
                                        # You can also set a custom flavour and style #dm_tool_bar.flavour_name in your css path
    
###### dm internal config ######

  version:                5.0.0_alpha1
  
  core:
    asset:                dm/core
  admin:
    asset:                dm/admin
  front:
    asset:                dm/front