default:

  i18n:                                 # internationalization
    cultures:             [ en ]        # Available cultures
  
  cache:                                # Cache management
    apc:                  true          # (RECOMMENDED) Use Apc if available on current server

  js:
    compress:             true          # (RECOMMENDED) Performance : Minifies javascripts and put them into a single compressed file
    cdn:                                # use cdn to load libraries
      enabled:            false         # Will use cdn to load javascript libraries faster
      lib.jquery:         'http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'
    
  css:
    compress:             true          # (RECOMMENDED) Performance : Minifies stylesheets and put them into a single compressed file
    
  seo:                                  # Search engine optimization configuration
    use_keywords:         true          # Keywords are useless for seo, but you can use them if you want
    truncate:                           # Max length for meta fields. Can not exceed 255 characters
      slug:               255
      name:               255
      title:              80
      h1:                 255
      description:        160
      keywords:           255
    sitemap:                            # see http://sitemaps.org
      path:               sitemap.xml   # relative path from web dir where diem will generate the sitemap

  orm:                                  # Doctrine ORM configuration
                                        # More configuration : please use ProjectConfiguration::configureDoctrine method
    identifier_fields:    [ name, title, slug, subject, id ] # Fields used to represent a record with a string
    cache_enabled:        true          # (RECOMMENDED) Use doctrine query cache. No side effect, automatic cache invalidation )
    cache_result_enabled: true          # (RECOMMENDED) Use doctrine result cache where query->dmCache() is called
    cache_result_enabled_default: false # Use doctrine result cache on every query ( performance gain, possible issues )
    
  backup:                               # keep a copy of files modified by Dm code editors
    enabled:              true          # (RECOMMENDED) enable backup
  
  web_debug:                            # web debug panel configuration
    only_html_response:   true          # will skip web debug panel display on non html response
    config_fast_dump:     true          # use print_r instead of sfYaml::dump to show config in web debug panel. ( ~40x faster )
    
  toolBar:
    flavour:              blue          # the toolbar flavour. Diem default values: grey, blue, green, brown, black
                                        # You can also set a custom flavour and style #dm_tool_bar.flavour_name in your themeAdmin css path
  media:
    default:              false         # default resource to use when using £media with an empty resource.
                                        # example: /uploads/default.jpg
  security:
    remember_cookie_name:               # defaults to "dm_remember_%project_name%"
    remember_key_expiration_age:        # defaults to 15 days

  locks:                                # whether to enable real time resource locks
    enabled:              <?php echo sfConfig::get('sf_debug') ? "false\n" : "true\n"; ?>
    timeout:              10            # time in seconds to consider a user is no more active on the page
 
###### dm internal config ######
  
  core:
    asset:                dm/core
  admin:
    asset:                dm/admin
  front:
    asset:                dm/front