Internal:
  Page:
    dmPage:
      admin:        false
    dmPageView:
      admin:        false
    dmArea:
      admin:        false
    dmZone:
      admin:        false
    dmWidget:
      admin:        false
    dmUser: