parameters:

  script_name_resolver.class: dmScriptNameResolver

  error_watcher.class:        dmErrorWatcher
  error_watcher.options:
    error_description_class:  dmErrorDescription

  media_tag_image.class:      dmMediaTagImage
  media_tag_flash.class:      dmMediaTagFlash
  media_tag_video.class:      dmMediaTagVideo
  media_tag_audio.class:      dmMediaTagAudio

  media_resource.class:       dmMediaResource

  search_engine.class:        dmSearchEngine

  search_index.class:         dmSearchIndex

  theme.class:                dmTheme

  stylesheet_compressor.class: dmStylesheetCompressor
  stylesheet_compressor.options:
    minify:                   true
    gz_compression:           true

  javascript_compressor.class: dmJavascriptCompressor
  javascript_compressor.options:
    minify:                   true
    gz_compression:           true

  auth_layout_helper.class:   dmAuthLayoutHelper

  cache_manager.class:        dmCacheManager
  cache_manager.options:
    meta_cache_class:         dmMetaCache

  doctrine_config.class:      dmDoctrineConfiguration

  filesystem.class:           dmFilesystem
  
  action_log.class:           dmActionLog
  action_log.options:
    file:                     'data/dm/log/action.log'
    entry_service_name:       action_log_entry
    ignore_models:            'DmError sfGuardRememberKey'
  
  action_log_entry.class:     dmActionLogEntry
  
  user_log.class:             dmUserLog
  user_log.options:
    file:                     'data/dm/log/user.log'
    entry_service_name:       user_log_entry
  
  user_log_entry.class:       dmUserLogEntry
    
  browser.class:              dmBrowser
    
  page_tree_watcher.class:    dmPageTreeWatcher
  
  file_backup.class:          dmFileBackup
  file_backup.options:
    dir:                      'data/dm/backup/filesystem'
    
  helper.class:               dmHelper
 
services:

  script_name_resolver:
    class:                    %script_name_resolver.class%
    shared:                   true
    arguments:                [ @context ]

  error_watcher:
    class:                    %error_watcher.class%
    shared:                   true
    arguments:                [ @dispatcher, @context, %error_watcher.options% ]

  media_tag:
    class:                    %media_tag.class%
    shared:                   false
    arguments:                [ %media_tag.source%, %user.theme%, %user.culture%, %request.context% ]

  media_resource:
    class:                    %media_resource.class%
    shared:                   false
    arguments:                [ %user.theme%, %user.culture%, %request.context% ]

  search_engine:
    class:                    %search_engine.class%
    shared:                   true
    arguments:                [ @dispatcher, @user, @logger, @service_container ]

  search_index:
    class:                    %search_index.class%
    shared:                   false
    arguments:                [ @dispatcher, @filesystem, @logger ]

  asset_config:
    class:                    %asset_config.class%
    shared:                   true
    arguments:                [ @dispatcher, @user ]

  theme:
    class:                    %theme.class%
    shared:                   false
    arguments:                [ @dispatcher, @filesystem, %request.context%, %theme.options% ]
    
  stylesheet_compressor:
    class:                    %stylesheet_compressor.class%
    shared:                   true
    arguments:                [ @dispatcher, @filesystem, %request.context%, %stylesheet_compressor.options% ]

  javascript_compressor:
    class:                    %javascript_compressor.class%
    shared:                   true
    arguments:                [ @dispatcher, @filesystem, %request.context%, %javascript_compressor.options% ]

  layout_helper:
    class:                    %layout_helper.class%
    shared:                   true
    arguments:
    arguments:                [ @dispatcher, @user, @response, @action_stack, @helper, %request.context% ]

  auth_layout_helper:
    class:                    %auth_layout_helper.class%
    shared:                   true
    arguments:                [ @dispatcher, @user, @response, @action_stack, @helper, %request.context% ]

  doctrine_config:
    class:                    %doctrine_config.class%
    shared:                   true
    arguments:                [ @doctrine_manager, @dispatcher, @cache_manager ]

  filesystem:
    class:                    %filesystem.class%
    shared:                   true
    arguments:                [ @dispatcher ]
      
  action_log:
    class:                    %action_log.class%
    shared:                   true
    arguments:                [ @dispatcher, @filesystem, @service_container, %action_log.options% ]
      
  action_log_entry:
    class:                    %action_log_entry.class%
    shared:                   false
    arguments:                [ @service_container ]
      
  user_log:
    class:                    %user_log.class%
    shared:                   true
    arguments:                [ @dispatcher, @filesystem, @service_container, %user_log.options% ]
      
  user_log_entry:
    class:                    %user_log_entry.class%
    shared:                   false
    arguments:                [ @service_container ]
      
  browser:
    class:                    %browser.class%
    shared:                   false
    arguments:                [ @dispatcher ]
      
  page_tree_watcher:
    class:                    %page_tree_watcher.class%
    shared:                   true
    arguments:                [ @dispatcher, @module_manager ]
      
  file_backup:
    class:                    %file_backup.class%
    shared:                   true
    arguments:                [ @dispatcher, @filesystem, %file_backup.options% ]
  
  helper:
    class:                    %helper.class%
    shared:                   true
    arguments:                [ @dispatcher, @user, @context, %request.context% ]
      
  cache_manager:
    class:                    %cache_manager.class%
    shared:                   true
    arguments:                [ @dispatcher ]