generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmSentMail
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_sent_mail
    with_doctrine_route: true
    config:
      actions: ~
      fields: {  }
      list:
        display:
          - =name
          - header
          - description
          - created_at
        sort:
          - created_at
          - desc
        table_method: joinAll
        table_count_method: ~
      filter:
        display:
          - name
          - header
          - description
          - created_at
      form:
        display:
          NONE: [name]
          Header: [header]
          Description: [description]
        class: DmSentMailAdminForm
        fields: {  }
      edit: ~
      new: ~
    sortable: false
