default:

  i18n:
    class:                  dmAdminI18n
    param:
      database:             default
      source:               dmMySQL
      debug:                false
      cache:
        class:              dmMetaCache
        
  routing:
    class:                  dmPatternRouting
    param:
      cache:
        class:              dmMetaCache
        param:
          automatic_cleaning_factor: 0
          cache_dir:                 %SF_CONFIG_CACHE_DIR%/routing
          lifetime:                  31556926
          prefix:                    %SF_APP_DIR%/routing

  request:
    class:                  dmWebRequest
    
  controller:
    class:                  dmFrontWebController

  response:
    class:                  dmAdminWebResponse
    
  logger:
    param:
      loggers:
        sf_web_debug:
          param:
            xdebug_logging: false
            web_debug_class: dmWebDebug
 
  view_cache:
    class:                  dmMetaCache