rendering:    ~

remember_me:
  class:      dmRememberMeFilter

security:
  class:      dmSecurityFilter

dm_init:
  class:      dmAdminInitFilter
  
cache:        ~

dm_seo:
  class:      dmAdminSeoValidationFilter
  enabled:    false

dm_html:
  class:      dmAdminHtmlFilter
  
execution:    ~