DmError:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    klass:                  { type: string(127), notnull: true }
    name:                   { type: string(255), notnull: true }
    description:            { type: string(65532) }
    module:                 { type: string(127), notnull: false }
    action:                 { type: string(127), notnull: false }
    uri:                    { type: string(255), notnull: true }
    env:                    { type: string(63), notnull: true }
    
DmSentMail:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    name:                   { type: string(255) }
    header:                 { type: string(65532) }
    description:            { type: string(65532) }
      
package:                    dmCorePlugin.lib.model.doctrine.log