DmAutoSeo:
  options:
    symfony:
      filter: false
  actAs:                    [Timestampable]
  columns:
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    module:                 { type: string(127), notnull: true, nospace: true }
    action:                 { type: string(127), notnull: true, nospace: true }
    slug:                   { type: string(255), notnull: true, nospace: true }
    name:                   { type: string(255), notnull: true }
    title:                  { type: string(255), notnull: true }
    h1:                     { type: string(255), notnull: false }
    description:            { type: string(255), notnull: false }
    keywords:               { type: string(255), notnull: false }
    strip_words:            { type: string(65532) }
  indexes:
    moduleAction:
      fields:               [ module, action ]
      type:                 unique

DmRedirect:
  actAs:                    [Timestampable]
  columns:
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    source:                 { type: string(255), unique: true, notnull: true, nospace: true }
    dest:                   { type: string(255), notnull: true }
      
package:                    dmCorePlugin.lib.model.doctrine.seo