DmSite:
  columns:
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    code:                   { type: string(255), notnull: true, unique: true }
    app_urls:               { type: string(65532) }
    
DmSetting:
  actAs:
    I18n:
      fields:               [value, setting_default]
  columns:
    dm_site_id:             { type: integer(4), notnull: true, unsigned: true }
    id:                     { type: integer(4), primary: true, autoincrement: true, unsigned: true }
    name:                   { type: string(255), notnull: true, unique: true }
    description:            { type: string(65532) }
    type:                   { type: string(127), notnull: true, default: input }
    options:                { type: string(65532) }
    value:                  { type: string(65532) }
    setting_group:          { type: string(255), notnull: true, default: '' }
    setting_default:        { type: string(65532), default: '' }
  relations:
    Site:
      class:                DmSite
      onDelete:             CASCADE
      foreignAlias:         Settings
      
package:                    dmCorePlugin.lib.model.doctrine.site