DmProfile:
  actAs:                    [Timestampable]
  columns:
    user_id:                { type: integer(4), notnull: true, unique: true, unsigned: true }
  relations:
    User:
      class:                sfGuardUser
      local:                user_id
      foreign:              id
      onDelete:             CASCADE

package:                    dmCorePlugin.lib.model.doctrine.user